openapi: 3.0.0
info:
  title: Egression Service
  version: 1.0.0
  description: >-
    Provides an on-demand service for querying materialized event records as
    well as retrieving materialized batch records by any data consumer through
    any of its interfaces. The materialized data is first standardized into
    consumer specific data format, then notification is sent to consumers and
    finally data is egressed on-demand. All egression interactions are recorded
    for auditing purposes. Every egression data instance is associated with the materialized data set Transaction ID, Time of Materialization and egression Transaction ID. Checksum is computed and provided for all egression data for integrity checks.
servers:
  - url: 'https://egression.{eipserver}:{port}/dataRetrieval'
    description: >- 
      Egression service endpoint per deployment environment.
    variables:
      eipserver:
        description: >- 
          Assigned at deployment time per the deployed environment.
        default: eipserver.tfs.com
      port:
        description: >-
          Assigned at deployment time per deployment and is unique for egression
          service.
        default: '8090'
paths:
  '/materializedData/{interfaceID}':
    get:
      description: >-
        Serve materialized data on-demand to the consumer  interface in consumer
        specific format.
      operationId: sendMaterializedDataByInterface
      parameters:
        - name: interfaceID
          in: path
          description: >-
            Identifies the interface of data sink uniquely by name and version.
            Unique identifier representing the interface name and version.
          required: true
          schema:
            type: string
        - name: dataSinkID
          in: query
          description: >-
            Identifies the consuming system uniquely by name and version.
          required: true
          allowEmptyValue: false
          schema:
            type: string
        - name: X-TFS-EgressionAPIID
          in: header
          description: >-
            Uniquely identifies the API implementation by name and version.
          required: true
          schema:
            type: string
            default: EgressionAPI-V1.0.0
        - name: X-TFS-EgressionAPIClientAccessKey
          in: header
          description: >-
            Uniquely identifies the applicatios permitted to interact with egression service. API access key is issued by the API Manager.
          required: true
          schema:
            type: string
        - name: X-TFS-InteractionGroupID
          in: header
          description: >-
            Unique tag identifying the instance of materialized data for a group of interfaces within a group.
          required: true
          schema:
            type: string
        - name: X-TFS-InteractionID
          in: header
          description: >-
            Unique client tag identifying the current interaction with the egression service.
          required: true
          schema:
            type: string
            format: UUID
        - name: X-TFS-TransactionID
          in: header
          description: >-
            Uniquely identifies the current instance of materialized data in current interaction. This value must have been received via egression notification.
          required: false
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: >-
            On sucessfully receiving and verifying the request and the
            materialized object is present.
          headers:
            X-TFS-TransactionID:
              description: >-
                Uniquely identifies the current instance of materialized data in current interaction.
              required: true
              schema:
                type: string
                format: UUID
            X-TFS-CheckSum:
              description: >-
                Hash (MD5) of the content. Client needs to verify the content
                against this checksum.
              required: true
              schema:
                type: string
            X-TFS-TimeOfMaterialization:
              description: >-
                Date and time data was materialized. The date-time format is as per RFC3339.
              required: true
              schema:
                type: string
                format: date-time
        '400':
          description: >-
            Bad Request. If the request is malformed or not understood by the
            egression service.
        '401':
          description: >-
            Unauthorized. If not authorized. It is expected the authorization is
            done by the gateway and any unauthorized requests are not passed to
            the egression service.
        '404':
          description: >- 
            Not found. If an unsupported interface id is specified.
        '412':
          description: >-
            Precondition Failed. If transactionId is present, but the egression
            server does not find the materlialized object identified by the
            transactionId.
      security:
        - egression_auth:
            - 'read:materializedObject'
