openapi: 3.0.0
info:
  title: 'Lease Late Charge Waiver Callback Service'
  version: v0.2
  description: >-
    Provides an on-demand service for Lease Late Charge Waiver Callback Service.
servers:
  - url: 'https://cep.{cepserver}:{port}/'
    description: 'Lease Account Customer Engagement Platform Service endpoint per deployment environment'
    variables:
      cepserver:
        description: >- 
          Assigned at deployment time per deployed environment.
        default: 'salesforce.com'
      port:
        description: >-
          Assigned at deployment time per deployment environment.
        default: '8080'
paths:
  '/leaseAccount/scheduledPaymentDueDate':
    put:
      description: 'Callback API to post Lease Late Charge Waiver Transaction Processing Results.'
      operationId: 'leaseLateChargeWaiverCallback'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LeaseDueDateCallback'
        description: 'Late Charge Waiver Callback Context & Resource Attributes'    
      responses:
        '200':
          description: 'Late Charge Waiver Transaction Request Processed Successfully'
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/LeaseDueDateCallbackAcknowledgement'
        '500':
          description: 'Error processing Late Charge Waiver Transaction Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaseDueDateCallbackAcknowledgement'          
components:
  schemas:         
    LeaseDueDateCallback:
      type: object
      required:
        - apiCallbackContext
        - financialAccountNumber  
      properties:
        apiCallbackContext:
          type: object
          description: >-
            Provides the detailed context for Lease Late Charge Waiver Callback
          properties:
            interactionID:
              type: string
              description: >-
                Globally Unique Identifier assigned by Client System representing the instance of an interaction with the Late Charge Waiver Service.
            apiCallbackInitiatedOn:
              type: string
              format: date-time
              example: 2017-07-21T17:32:28Z              
              description: >-
                Date & Time at which Callback API was Initiated by Server in ISO 8601 format. 
            apiInitiatingPartyID:
              type: string
              description: >-
                Unique Identifier representing the Party/System Initiating the API.    
            apiReactingPartyID:
              type: string
              description: >-
                Unique Identifier representing the Party/System Reacting to the API.                                 
            apiCallbackCode:
              type: string
              description: >-
                Response Code from the API Service indicating the status of Late Charge Waiver transaction.
            apiCallbackDescription:
              type: string
              description: >-
                Provides the description for Response Code from the API Service indicating the status of Late Charge Waiver transaction                
        apiExceptionContext:
          properties:
            apiExceptionCode:
              type: string
              description: >-
                Exception code from the Late Charge Waiver Service indicating that the Late Charge Waiver transaction was not processed successfully.
            apiExceptionDescription:
              type: string
              description: >-
                Provides the description for Exception Code from the Late Charge Waiver Service indicating that the Late Charge Waiver transaction was not processed successfully
            apiResourceExceptionDetail:
              type: array
              items:
                type: object
                description: >-
                  Provides the reference to the Resource Attributes that caused the Exception
                properties:
                  resourceAttributeName:
                    type: string
                    description: >-
                      Name of the Resource Attribute that cased the Exception.                    
                  resourceAttributeValue:
                    type: string  
                    description: >-
                      Value of the Resource Attribute that cased the Exception.                      
                  resourceAttributeExceptionCode:
                    type: string            
                    description: >-
                      Exception Code representing the type of error caused by the given Resource Attribute.                    
                  resourceAttributeExceptionDescription:
                    type: string  
                    description: >-
                      Description of the Exception Code representing the type of error caused by the given Resource Attribute.                    
        financialAccountNumber:
          type: string
          description: >-
            Unique Identifier for a Lease Account within Toyota Financial Services
            Composite Key - [Region][Branch][Lease Number]
                            [99][999][AAAAA]
    LeaseDueDateCallbackAcknowledgement:
      properties:            
        apiAcknowledgementContext:
          properties:
            interactionID:
              type: string
              description: >-
                Globally Unique Identifier assigned by Client System representing the instance of an interaction with the Late Charge Waiver Service.
            apiAcknowledgementInitiatedOn:
              type: string
              format: date-time
              example: 2017-07-21T17:32:28Z              
              description: >-
                Date & Time at which API Acknowledgement was Initiated by Late Charge Waiver Service in ISO 8601 format.      
            apiAcknowledgementCode:
              type: string
              description: >-
                Return Code from Client indicating that the Late Charge Waiver Callback was processed successfully.
            apiAcknowledgementDescription:
              type: string
              description: >-
                Provides the description for Return Code from Client indicating that the Late Charge Waiver Callback was processed successfully.
        apiExceptionContext:
          properties:
            apiExceptionCode:
              type: string
              description: >-
                Exception code from Client indicating that the Late Charge Waiver Callback was not processed successfully.
            apiExceptionDescription:
              type: string
              description: >-
                Provides the description for Exception Code from Client indicating that the Late Charge Waiver Callback was not processed successfully
            apiResourceExceptionDetail:
              type: array
              items:
                type: object
                description: >-
                  Provides the reference to the Resource Attributes that caused the Exception
                properties:
                  resourceAttributeName:
                    type: string
                    description: >-
                      Name of the Resource Attribute that cased the Exception.                    
                  resourceAttributeValue:
                    type: string  
                    description: >-
                      Value of the Resource Attribute that cased the Exception.                      
                  resourceAttributeExceptionCode:
                    type: string            
                    description: >-
                      Exception Code representing the type of error caused by the given Resource Attribute.                    
                  resourceAttributeExceptionDescription:
                    type: string  
                    description: >-
                      Description of the Exception Code representing the type of error caused by the given Resource Attribute.